/**
 * The load-bearing "Synthetic data" pill (CLAUDE.md: "the banner in the UI is not decorative; it is
 * load-bearing"). Every vendor, shipment, manifest, and HTS clause in this app is generated by the
 * repo's config scripts - this pill states that plainly so the demo is never mistaken for real data.
 */
export function SyntheticDataPill() {
  return (
    <span
      className="inline-flex shrink-0 items-center gap-1.5 whitespace-nowrap rounded-full border border-warn/30 bg-warn/10 px-2.5 py-1 text-[11px] font-medium text-warn"
      title="All vendors, shipments, manifests, and HTS clauses are synthetic. No real trade data exists in this demo."
    >
      <span className="h-1.5 w-1.5 rounded-full bg-warn" aria-hidden="true" />
      Synthetic data
    </span>
  );
}
